"""Fit the SFU coefficient tables and write them out in both worlds.

    python -m bpuref.gen_sfu_rom            # (re)generate
    python -m bpuref.gen_sfu_rom --check    # fail if the checked-in files are stale

Outputs (never edit by hand):
    model/bpuref/sfu_tables_data.py     the frozen tables bpuref.sfu uses
    rtl/sfu/bpu_sfu_rom_pkg.sv          coefficient widths
    rtl/sfu/bpu_sfu_rom.sv              combinational ROM with the same contents

The checked-in data file is the spec. --check compares the RTL ROM against it;
a refit (fit_tables) is only needed when the approximation itself changes.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

from . import sfu

HERE = Path(__file__).resolve().parent
DATA = HERE / "sfu_tables_data.py"
RTL = HERE.parents[1] / "rtl" / "sfu"
TABLE_NAMES = ["rcp", "rsqrt_even", "rsqrt_odd", "exp2", "log_pos", "log_neg"]


def _signed_width(values) -> int:
    lo, hi = int(np.min(values)), int(np.max(values))
    w = 1
    while not (-(1 << (w - 1)) <= lo and hi < (1 << (w - 1))):
        w += 1
    return w


def render_data(t: np.ndarray) -> str:
    lines = ['"""Frozen SFU coefficient tables (generated by gen_sfu_rom.py; do not edit).',
             "",
             "SFU_TABLES[table][segment] = (c0, c1, c2); see bpuref.sfu.poly_eval.",
             '"""', "", "SFU_TABLES = ("]
    for k, name in enumerate(TABLE_NAMES):
        lines.append(f"    (  # {k}: {name}")
        for c in t[k]:
            lines.append(f"        ({int(c[0])}, {int(c[1])}, {int(c[2])}),")
        lines.append("    ),")
    lines.append(")")
    return "\n".join(lines) + "\n"


def render_rtl(t: np.ndarray) -> tuple[str, str]:
    w0, w1, w2 = (_signed_width(t[:, :, i]) for i in range(3))
    pkg = f"""// Generated by compute/model/bpuref/gen_sfu_rom.py -- do not edit.
package bpu_sfu_rom_pkg;
  /* verilator lint_off UNUSEDPARAM */
  localparam int unsigned SfuC0W = {w0};
  localparam int unsigned SfuC1W = {w1};
  localparam int unsigned SfuC2W = {w2};
  /* verilator lint_on UNUSEDPARAM */
endpackage
"""
    rows = []
    for k in range(t.shape[0]):
        for i in range(t.shape[1]):
            c0, c1, c2 = (int(v) for v in t[k, i])
            def lit(v, w):
                return f"-{w}'sd{-v}" if v < 0 else f"{w}'sd{v}"
            rows.append(f"      10'd{k * 128 + i}: {{c0_o, c1_o, c2_o}} = "
                        f"{{{lit(c0, w0)}, {lit(c1, w1)}, {lit(c2, w2)}}};")
    rom = f"""// Generated by compute/model/bpuref/gen_sfu_rom.py -- do not edit.
// SFU quadratic coefficients: {len(TABLE_NAMES)} tables x 128 segments
// ({", ".join(f"{k}={n}" for k, n in enumerate(TABLE_NAMES))}).
module bpu_sfu_rom
  import bpu_sfu_rom_pkg::*;
(
  input  logic [2:0]               table_i,
  input  logic [6:0]               idx_i,
  output logic signed [SfuC0W-1:0] c0_o,
  output logic signed [SfuC1W-1:0] c1_o,
  output logic signed [SfuC2W-1:0] c2_o
);

  always_comb begin
    unique case ({{table_i, idx_i}})
{chr(10).join(rows)}
      default: {{c0_o, c1_o, c2_o}} = '0;
    endcase
  end

endmodule
"""
    return pkg, rom


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify generated RTL matches the data")
    ap.add_argument("--refit", action="store_true", help="refit tables instead of using the data file")
    args = ap.parse_args(argv)

    if args.refit or not DATA.exists():
        t = sfu.fit_tables()
        if not args.check:
            DATA.write_text(render_data(t), newline="\n")
    else:
        t = sfu.tables()

    pkg, rom = render_rtl(t)
    targets = {RTL / "bpu_sfu_rom_pkg.sv": pkg, RTL / "bpu_sfu_rom.sv": rom}
    if args.check:
        stale = [p.name for p, text in targets.items() if not p.exists() or p.read_text() != text]
        if stale:
            print("stale generated files:", ", ".join(stale), "-> run python -m bpuref.gen_sfu_rom")
            return 1
        print("SFU ROM up to date")
        return 0
    RTL.mkdir(parents=True, exist_ok=True)
    for path, text in targets.items():
        path.write_text(text, newline="\n")
        print("wrote", path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
