// Generated by compute/model/bpuref/gen_sfu_rom.py -- do not edit.
package bpu_sfu_rom_pkg;
  /* verilator lint_off UNUSEDPARAM */
  localparam int unsigned SfuC0W = 32;
  localparam int unsigned SfuC1W = 25;
  localparam int unsigned SfuC2W = 18;
  /* verilator lint_on UNUSEDPARAM */
endpackage
